# Generated by Django 3.1.3 on 2021-11-18 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiaires',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=200)),
                ('Prenom', models.CharField(max_length=200)),
                ('Email', models.EmailField(blank=True, max_length=200, null=True)),
                ('Telephone', models.IntegerField(blank=True, max_length=20, null=True)),
                ('Nb_parts', models.CharField(choices=[('Plus de 65 ans', 'Plus de 65 ans'), ('15-25 ans', '15-25 ans'), ('0-3 ans', '0-3 ans'), ('4-14 ans', '4-14 ans'), ('25-64 ans', '25-64 ans')], default='1', max_length=200)),
                ('Mot_mairie', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='1', max_length=200)),
                ('Carte_donnee', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='1', max_length=200)),
                ('Remarques', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=200)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Static/images')),
                ('Unite', models.CharField(choices=[('Kilo', 'Kilo'), ('Unité', 'Unité'), ('Litre', 'Litre')], default='2', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=200)),
                ('Quantite', models.FloatField(blank=True, default='0', null=True)),
                ('Categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gstock.categories')),
            ],
        ),
    ]
