# Generated by Django 3.1.3 on 2021-11-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gstock', '0002_auto_20211118_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaires',
            name='Nb_parts',
            field=models.CharField(choices=[('15-25 ans', '15-25 ans'), ('4-14 ans', '4-14 ans'), ('Plus de 65 ans', 'Plus de 65 ans'), ('0-3 ans', '0-3 ans'), ('25-64 ans', '25-64 ans')], default='1', max_length=200),
        ),
        migrations.AlterField(
            model_name='categories',
            name='Unite',
            field=models.CharField(choices=[('Litre', 'Litre'), ('Unité', 'Unité'), ('Kilo', 'Kilo')], default='2', max_length=200),
        ),
    ]
