# Generated by Django 3.1.3 on 2021-11-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gstock', '0003_auto_20211118_1409'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produits',
            new_name='Stock',
        ),
        migrations.AlterField(
            model_name='beneficiaires',
            name='Nb_parts',
            field=models.CharField(choices=[('4-14 ans', '4-14 ans'), ('25-64 ans', '25-64 ans'), ('15-25 ans', '15-25 ans'), ('Plus de 65 ans', 'Plus de 65 ans'), ('0-3 ans', '0-3 ans')], default='1', max_length=200),
        ),
        migrations.AlterField(
            model_name='categories',
            name='Unite',
            field=models.CharField(choices=[('Kilo', 'Kilo'), ('Litre', 'Litre'), ('Unité', 'Unité')], default='2', max_length=200),
        ),
    ]
