# Generated by Django 3.1.3 on 2021-11-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gstock', '0004_auto_20211121_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaires',
            name='Nb_parts',
            field=models.CharField(choices=[('Plus de 65 ans', 'Plus de 65 ans'), ('0-3 ans', '0-3 ans'), ('25-64 ans', '25-64 ans'), ('4-14 ans', '4-14 ans'), ('15-25 ans', '15-25 ans')], default='1', max_length=200),
        ),
        migrations.AlterField(
            model_name='beneficiaires',
            name='Nom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='Unite',
            field=models.CharField(choices=[('Unité', 'Unité'), ('Kilo', 'Kilo'), ('Litre', 'Litre')], default='2', max_length=200),
        ),
    ]
