# Generated by Django 3.1.3 on 2021-11-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gstock', '0008_auto_20211123_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaires',
            name='Nb_parts',
            field=models.CharField(blank=True, choices=[('0-3 ans', '0-3 ans'), ('25-64 ans', '25-64 ans'), ('4-14 ans', '4-14 ans'), ('Plus de 65 ans', 'Plus de 65 ans'), ('15-25 ans', '15-25 ans')], default='1', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='Unite',
            field=models.CharField(choices=[('Litre', 'Litre'), ('Unité', 'Unité'), ('Kilo', 'Kilo')], default='2', max_length=200),
        ),
    ]
