# Generated by Django 3.1.3 on 2021-11-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gstock', '0009_auto_20211123_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaires',
            name='Carte_donnee',
            field=models.CharField(choices=[('Non', 'Non'), ('Oui', 'Oui')], default='1', max_length=200),
        ),
        migrations.AlterField(
            model_name='beneficiaires',
            name='Mot_mairie',
            field=models.CharField(choices=[('Non', 'Non'), ('Oui', 'Oui')], default='1', max_length=200),
        ),
        migrations.AlterField(
            model_name='beneficiaires',
            name='Nb_parts',
            field=models.CharField(blank=True, choices=[('15-25 ans', '15-25 ans'), ('0-3 ans', '0-3 ans'), ('4-14 ans', '4-14 ans'), ('Plus de 65 ans', 'Plus de 65 ans'), ('25-64 ans', '25-64 ans')], default='1', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='Unite',
            field=models.CharField(choices=[('Litre', 'Litre'), ('Kilo', 'Kilo'), ('Unité', 'Unité')], default='2', max_length=200),
        ),
    ]
