# Generated by Django 3.1.3 on 2021-11-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gstock', '0010_auto_20211123_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='Seuil_alerte',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='beneficiaires',
            name='Nb_parts',
            field=models.CharField(blank=True, choices=[('Plus de 65 ans', 'Plus de 65 ans'), ('15-25 ans', '15-25 ans'), ('4-14 ans', '4-14 ans'), ('25-64 ans', '25-64 ans'), ('0-3 ans', '0-3 ans')], default='1', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='Unite',
            field=models.CharField(choices=[('Kilo', 'Kilo'), ('Litre', 'Litre'), ('Unité', 'Unité')], default='2', max_length=200),
        ),
    ]
