# Generated by Django 3.1.3 on 2021-12-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gstock', '0011_auto_20211124_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaires',
            name='Carte_donnee',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='1', max_length=200),
        ),
        migrations.AlterField(
            model_name='beneficiaires',
            name='Mot_mairie',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='1', max_length=200),
        ),
        migrations.AlterField(
            model_name='beneficiaires',
            name='Nb_parts',
            field=models.CharField(blank=True, choices=[('25-64 ans', '25-64 ans'), ('4-14 ans', '4-14 ans'), ('Plus de 65 ans', 'Plus de 65 ans'), ('0-3 ans', '0-3 ans'), ('15-25 ans', '15-25 ans')], default='1', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='Unite',
            field=models.CharField(choices=[('Kilo', 'Kilo'), ('Unité', 'Unité'), ('Litre', 'Litre')], default='2', max_length=200),
        ),
    ]
