# Generated by Django 3.1.3 on 2022-07-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gstock', '0013_auto_20220726_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaires',
            name='Nb_parts',
            field=models.CharField(blank=True, choices=[('25-64 ans', '25-64 ans'), ('15-25 ans', '15-25 ans'), ('4-14 ans', '4-14 ans'), ('0-3 ans', '0-3 ans'), ('Plus de 65 ans', 'Plus de 65 ans')], default='1', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='Unite',
            field=models.CharField(choices=[('Kilo', 'Kilo'), ('Unité', 'Unité'), ('Litre', 'Litre')], default='2', max_length=200),
        ),
    ]
