# Generated by Django 4.2.11 on 2024-04-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gstock', '0026_alter_beneficiaires_nb_parts_alter_categories_unite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaires',
            name='Nb_parts',
            field=models.CharField(blank=True, choices=[('25-64 ans', '25-64 ans'), ('0-3 ans', '0-3 ans'), ('15-25 ans', '15-25 ans'), ('Plus de 65 ans', 'Plus de 65 ans'), ('4-14 ans', '4-14 ans')], default='1', max_length=200, null=True),
        ),
    ]
