# Generated by Django 4.2.11 on 2024-04-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gstock', '0027_alter_beneficiaires_nb_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaires',
            name='Carte_donnee',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='1', max_length=200),
        ),
        migrations.AlterField(
            model_name='beneficiaires',
            name='Mot_mairie',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='1', max_length=200),
        ),
        migrations.AlterField(
            model_name='categories',
            name='Unite',
            field=models.CharField(choices=[('Kilo', 'Kilo'), ('Litre', 'Litre'), ('Unité', 'Unité')], default='2', max_length=200),
        ),
    ]
